[package]
name = "rust-lambda"
version = "0.1.0"
authors = ["James Richardson <james@time4tea.net>"]
edition = "2018"

[lib]
name="lambda_utils"

[dependencies]
lambda_runtime = "0.2.1"
lambda_runtime_core = "0.1.2"
serde = { version = "^1.0", features = ["derive"] }
http = "0.2.2"